### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by mvorisis** [aciidb0mb3r/SwiftMQTT#18]
Hi 

Happy new Year!

First of all thank you for this great library! 
I developed an app that uses hivemq server(local with terminal) and I was wondering how to send push notifications when my app is closed.
When I close my app I see in terminal myuser is disconnected
So my question is how can I stop disconnection when I terminate the app or what documentation could you recommend to me to accomplish that.

Thanks in advance

**Comment by bhargavg** [comment]
The socket connections will be terminated once the app is closed. I suggest you use apple's APNS server for sending push notifications.

**Comment by mvorisis** [comment]
Hi thanks for your answer can you provide me any documentation if you know that I can start with.?

**Comment by mvorisis** [comment]
Finally I found out that I can customize my own plugin (with hivemq at least) and I used pushy to do it
