### ISSUE TITLE
Interupted messages

### ISSUE THREAD

**Issue by mvorisis** [aciidb0mb3r/SwiftMQTT#22]
Hi 

I put a print under `mqttDidReceive`  to have logs in xcode, then I tried on simulator and put the app in the background and sent a message that appeared in the log.

And now here comes the problem I tried the same thing on my iphone but when the app was in the background nothing came, and when I reopened it all messages came right a way.

Any thought of why is this happening?

I also asked in [stackoverflow](http://stackoverflow.com/questions/43769717/background-updates-work-on-simulator-but-not-in-my-iphone?noredirect=1#comment74582397_43769717)

**Comment by adolfo** [comment]
MQTT won't work in the background, at least not for an extended period of time. When the app enters the background you should disconnect from the MQTT server and when reentering the forground you reconnect and resubscribe. During this time you should rely on other methods to communicate with your app, i.e. push.

**Comment by mvorisis** [comment]
Thanks for the quick answer,

I just was so curious that it would work on simulator and not on Iphone,

Anyways I will disconnect it and reconnect properly

Thanks again
