### ISSUE TITLE
Do this support RabbitMQ connection?

### ISSUE THREAD

**Issue by netgfx** [aciidb0mb3r/SwiftMQTT#9]
Has anyone tested this library with RabbitMQ?

**Comment by adolfo** [comment]
@netgfx I have not tested it, but looking at the RabbitMQ documentation, it does say that an MQTT plugin is available.

https://www.rabbitmq.com/mqtt.html

**Comment by netgfx** [comment]
ok thanks, I will run some tests and report back here in case anyone else is interested as well.

**Comment by netgfx** [comment]
I have tried with a server with RabbitMQ and the MQTT plugin, and it works nicely.
